### ISSUE TITLE
fails to install on FreeBSD 11.0

### ISSUE THREAD

**Issue by gregf** [sabnzbd/sabyenc#1]
Hi we talked on reddit a while back when you made your announcement for the new alpha 2.0

I just got around to installing it and I was unable to install sabyenc on FreeBSD it fails to compile.

```
    Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z8H_49/sabyenc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fg57Uq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'sabyenc' extension
    creating build
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-2.7
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-2.7/src
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c src/sabyenc.c -o build/temp.freebsd-11.0-RELEASE-p8-amd64-2.7/src/sabyenc.o -O2
    src/sabyenc.c:169:21: warning: passing 'Byte *' (aka 'unsigned char *') to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                strncpy(*filename_out, start_loc, end_loc - start_loc);
                        ^~~~~~~~~~~~~
    /usr/include/string.h:101:32: note: passing argument to parameter here
    char    *strncpy(char * __restrict, const char * __restrict, size_t);
                                      ^
    src/sabyenc.c:170:36: warning: passing 'Byte *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                (*filename_out)[strlen(*filename_out)] = ZERO;
                                       ^~~~~~~~~~~~~
    /usr/include/string.h:95:28: note: passing argument to parameter here
    size_t   strlen(const char *) __pure;
                                ^
    src/sabyenc.c:261:40: warning: assigning to 'char *' from 'Byte *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
                                crc_holder = (Byte *) calloc(strlen(cur_char)+1, sizeof(Byte *));
                                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/sabyenc.c:264:40: warning: assigning to 'char *' from 'Byte *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
                                crc_holder = (Byte *) realloc(crc_holder, strlen(cur_char)+strlen(crc_holder)+1);
                                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/sabyenc.c:352:28: warning: assigning to 'char *' from 'Byte *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
            search_placeholder = (Byte *) calloc(cur_len, sizeof(Byte *));
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/sabyenc.c:363:32: warning: assigning to 'char *' from 'Byte *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
                search_placeholder = (Byte *) realloc(search_placeholder, cur_len);
                                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    6 warnings generated.
    creating build/lib.freebsd-11.0-RELEASE-p8-amd64-2.7
    cc -shared -lpthread -L/usr/local/lib -fstack-protector build/temp.freebsd-11.0-RELEASE-p8-amd64-2.7/src/sabyenc.o -L/usr/local/lib -lpython2.7 -o build/lib.freebsd-11.0-RELEASE-p8-amd64-2.7/sabyenc.so
    running install_lib
    copying build/lib.freebsd-11.0-RELEASE-p8-amd64-2.7/sabyenc.so -> /usr/local/lib/python2.7/site-packages
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/sabyenc.so'

    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z8H_49/sabyenc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fg57Uq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Z8H_49/sabyenc/

```

**Comment by gregf** [comment]
Oh just so you are aware I used pip install to do this.

**Comment by Safihre** [comment]
The building is fine, just warnings.
It's your permissions that are wrong:
```
error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/sabyenc.so'
```
Just need to run the installer as sudo/root.

**Comment by gregf** [comment]
DOH! I can't believe I did something that stupid. Sorry to waste
your time!




On Mon, Mar 6, 2017, at 01:25 PM, Safihre wrote:

> The building is fine, just warnings.

>  It's your permissions that are wrong:


> error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-
> packages/sabyenc.so'
>
> Just need to run the installer as sudo/root.



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 

> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5-
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/sabnzbd/s-
> abyenc","title":"sabnzbd/sabyenc","subtitle":"GitHub repository","main_image_url":"
> https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
> in GitHub","url":"
> https://github.com/sabnzbd/sabyenc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Safihre
> in #1: The building is fine, just warnings.\r\nIt's your permissions
> that are wrong:\r\n```\r\nerror: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-
> packages/sabyenc.so'\r\n```\r\nJust need to run the installer as
> sudo/root."}],"action":{"name":"View Issue","url":"
> https://github.com/sabnzbd/sabyenc/issues/1#issuecomment-284485330"}}}
> script>



Links:

  1. https://github.com/sabnzbd/sabyenc/issues/1#issuecomment-284485330

**Comment by gregf** [comment]
The alpha is so much faster, thank you for your hard work.

**Comment by sanderjo** [comment]
@gregf Can you share the exact commands to install sabyenc on FreeBSD? I will then include that on https://sabnzbd.org/sabyenc

**Comment by gregf** [comment]
I did `sudo pip install sabyenc`

**Comment by sanderjo** [comment]
> su pip install sabyenc

That's all? So "pip" is installed by default on FreeBSD? And no need for python-dev aka python-devel ?

**Comment by gregf** [comment]
Sorry I wasn't thinking you would need more detail than though I don't know why.

```
su - <password>
pkg install python
pkg install python27-2.7.13_1
pkg install py27-pip-9.0.1
ln -s /usr/local/bin/python /usr/bin/python
pip install --upgrade sabyenc
```

**Comment by sanderjo** [comment]
OK, thanks: now on https://sabnzbd.org/wiki/extra/sabyenc.html
![screenshot from 2017-03-06 20-13-27](https://cloud.githubusercontent.com/assets/1273502/23625422/65d39dbc-02a9-11e7-9edf-33495fe5b126.png)

Correct?

**Comment by gregf** [comment]
LGTM if anyone complains about issues on freebsd feel free to tag me in on the issue. Happy to help out. Just joined irc.
