### ISSUE TITLE
New repo for Sabyenc3? 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabyenc#12]
I adapted Sabyenc to work on Python 3, but now it's incompatible with Python 2.
I went ahead and renamed it to `sabyenc3` in Pypi so running `pip install sabyenc` doesn't accidentally fetch the wrong version.
But where should I keep the source code? It's currently in a branch here at `sabyenc`, but maybe it should be a whole new repo?
@sanderjo @jcfp @jeffgeorge @thezoggy

**Comment by sanderjo** [comment]
So you will need to install it with "pip install sabyenc3"? Looks clear to me. And a seperate repo too.

FWIW: Pity the current sabyenc (for python2) is already at version 3.3.5 ... that might confuse

**Comment by thezoggy** [comment]
is there really any other project that uses sabyenc ? (if your going to make it agnostic.. prob should have renamed it from having sab in it) but the way it currently is and used.. it really can just stay part of sab code..  just  make it a submodule (like any other 3rd party lib)

**Comment by Safihre** [comment]
It will probably only get more specific to SABnzbd. But even as a submodule, it needs a repo somewhere.

**Comment by jcfp** [comment]
if the only change is moving from py2 to py3 but it is otherwise a plug-in replacement I wouldn't even bother with separate repos. If there's actually anyone out there using sabyenc for something else they can work with the last commit and/or branch that was py2-compatible.

**Comment by Safihre** [comment]
Alright, then it will stay on this repo.
I can also maybe increase the version number of `sabyenc3` to `4.0.0` instead of starting from `1.x.x` again to match `sabyenc` better.

**Comment by jcfp** [comment]
> I can also maybe increase the version number of `sabyenc3` to `4.0.0` instead of starting from `1.x.x` again to match `sabyenc` better.

definitely, it is a newer version of the same codebase after all

**Comment by thezoggy** [comment]
especially since you are doing sab w/python3 in the same repo.. makes sense to keep it in the same family so it makes those that want to support python 2 / 3 variants they just have to set boundaries on what version to grab (or you know just stick them in branches)
