### ISSUE TITLE
release 4.0.1

### ISSUE THREAD

**Issue by cheese1** [sabnzbd/sabyenc#16]
could you create a release 4.0.1
there is no download under "releases"

and could you rename the directory inside the tar-file to be sabyenc3, to match the new name

**Comment by Safihre** [comment]
I pushed the tag, for some reason it was removed.
But I don't think I can control the name of the folder inside the tar/zip that GitHub creates, only by renaming the whole repository.
This I can only do after releasing Python 3 version of SABnzbd.
The PyPi version has everything nicely put together, with right names: https://pypi.org/project/sabyenc3
