### ISSUE TITLE
Unable to pip install on Windows with Python 3.8

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabyenc#17]
Fails during build due to no Visual Studio on target system.  Probably just needs a new build on PyPi for 3.8.

**Comment by Safihre** [comment]
Waiting for AppVeyor support for Python 3.8, to keep the pipelines consistent:
https://github.com/appveyor/ci/issues/3142

**Comment by Safihre** [comment]
The files have been added: https://pypi.org/project/sabyenc3/#files
