### ISSUE TITLE
Encoding support

### ISSUE THREAD

**Issue by fetzerms** [sabnzbd/sabyenc#2]
The module description states, that this is yEnc **Encoding**/Decoding for Python. But I do not see any Decoding functions offered by the header file (nor by the source). 

Is this a feature that will be added? Or is this module aimed purely at sabnzbd, and encoding/posting support is not planned?

**Comment by Safihre** [comment]
You are absolutely right: there is no encoding support and there also won't be (at least, I won't make it, but other are free to add it of course).
In a next iteration I will remove any references to Encoding!

**Comment by fetzerms** [comment]
Ok. I suggest to keep this issue open and close it, when the references have been removed.
