### ISSUE TITLE
Fails to build on 32bit

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabyenc#22]
@animetosho I am using `cibuildwheels` to do the cross compiling, it looks quite promising. Will have to validate if it actually compiled everything correctly with the custom build step.

One problem is that both on Windows and Linux it fails to compile for 32bit with the same error:
Windows: https://github.com/sabnzbd/sabyenc/runs/5305443982?check_suite_focus=true#step:5:209
Linux: https://github.com/sabnzbd/sabyenc/runs/5304913537?check_suite_focus=true#step:5:707
It's probably something that you know very easy how to fix?

**Comment by animetosho** [comment]
Weird that I never noticed it in the past. Would you be able to see if [this change](https://github.com/animetosho/node-yencode/commit/bb13541cad51d539fcbd93154a7ef53bd1b72052) fixes it?  
Thanks for finding it!

Also noticed that the MSVC compile includes the `/LTCG` parameter - I've seen issues with MSVC getting confused with the target ISA, when developing ParPar, when LTCG is enabled and different `/arch` flags being specified for individual source files. I don't know if it's a problem here, and I can't seem to find anyone reporting the issue in general.  
Still, if you want to be on the safe side, you can add the `/GL-` flag [to this line](https://github.com/sabnzbd/sabyenc/blob/0652748ad754342759be50e2ffc2c4786b0969a9/setup.py#L46).  
I might check the case where I saw MSVC generating wrong instructions to see if it's actually an issue, or something I messed up.

**Comment by Safihre** [comment]
It worked! 
https://github.com/sabnzbd/sabyenc/actions/runs/1891465189
Maybe you can see if you see any other things in all the compile-steps for all the archs/platforms?
Seems only `aarch64` is supported for pre-build packages, so it should include NEON without problem.

On macOS there is this special `universal2` format that includes x64 and aarch64, but we don't detect it in `setup.py` as such. So will probably add special detection for that so it includes ARM options.

**Comment by animetosho** [comment]
Good to know it works.

If your build tool supports cross compiling, see if it provides a way to determine the arch it's building for. Otherwise you may be stuck with some workaround as you mention.

**Comment by animetosho** [comment]
>  I might check the case where I saw MSVC generating wrong instructions to see if it's actually an issue, or something I messed up.

Investigated this more. Probably my fault, though somewhat weird.  
If you ever want to enable LTCG (i.e. remove the `/GL-` switch) in the future, you can try [this change](https://github.com/animetosho/node-yencode/commit/6976dbddd3a973d26efef1f2ef30b3fca80a96c9).  
(LTCG is probably enabled by default because it can provide some further optimisations, though I doubt it matters much here)

**Comment by Safihre** [comment]
I didn't see any real change with or without the switch, performance was about the same.

**Comment by animetosho** [comment]
Sorry if I was too confusing: it should have no effect on performance, it's more of a 'correctness' thing.

**Comment by Safihre** [comment]
Ok! Applied them.
