### ISSUE TITLE
feature/ga on Linux: coredump 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabyenc#25]
```
sander@haring1:~/git/sabyenc$ tests/speed_compare.py
4.0.1
---
     yEnc C New  took   619 ms
---
```

```
sander@haring1:~/git/sabyenc$ python3 setup.py build
sander@haring1:~/git/sabyenc$ cp build/lib*/*so tests/
sander@haring1:~/git/sabyenc$ tests/speed_compare.py
Illegal instruction (core dumped)
```

Let's see:

```
sander@haring1:~/git/sabyenc/tests$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabyenc3
Illegal instruction (core dumped)
sander@haring1:~/git/sabyenc/tests$
```

So only the import causes the core dump. Not good.

And to be sure: the main repo just works (6 times faster)

```
sander@haring1:~/git/yenc_poging2$ python3 tests/speed_compare.py
5.0.0
---
     yEnc C New  took   104 ms
---
```

**Comment by Safihre** [comment]
@animetosho Do you know how to best debug this? I tried running `pytest` on GitHub actions, but it succeeds for Ubuntu.
Additionally, it shows coredumps for macOS unless I change `-O3` to `-O0`.
Really strange..

**Comment by sanderjo** [comment]
update:

After really installing with `sudo python3 setup.py install`, I can run speedtest.py. No more coredump.

So the trick with the local cp of the sabyenc.so causes the coredump?

**Comment by animetosho** [comment]
You can diagnose the problem using `gdb` by running something like:

```
gdb python3
run [arguments]
```

Use the `bt` command to get a stack trace, when it crashes.  
You can also use [one of these](https://stackoverflow.com/questions/1902901/show-current-assembly-instruction-in-gdb) to show the instruction it halted on, and see if your CPU supports that instruction.

> EDIT: Fixed the -O3 problem, it was an edit that I made to your code which was not correct!  
So the trick with the local cp of the sabyenc.so causes the coredump?

Neither of these should cause the issue.

**Comment by sanderjo** [comment]
FWIW / For Google Reference: My dmesg says:

`[vr feb 25 15:01:11 2022] traps: python3[742000] trap invalid opcode ip:7ff9a2e7ddbf sp:7ffdf6721c40 error:0 in sabyenc3.cpython-38-x86_64-linux-gnu.so[7ff9a2e69000+1c000]`

`[vr feb 25 15:28:46 2022] traps: python3[742946] trap invalid opcode ip:7fa2fd689837 sp:7ffc0b0f35f0 error:0 in sabyenc3.cpython-38-x86_64-linux-gnu.so[7fa2fd619000+7f000]`

**Comment by animetosho** [comment]
Ah, probably was the CFLAGS array not being cloned.
