### ISSUE TITLE
SABYenc disabled: no correct version found! (Found v5.0.1, expecting v4.0.0)

### ISSUE THREAD

**Issue by fryfrog** [sabnzbd/sabyenc#28]
Looks like sabnzbd 3.5.1 does not like sabyenc3 5.0.1. :)

**Comment by Safihre** [comment]
Yes of course...
Check the `requirements.txt` shipped with 3.5.1, it will show  `sabyenc3==4.0.2`.

**Comment by fryfrog** [comment]
@Safihre, I assume there's going to be a future sabnzbd that depends on this? I maintain the AUR package for sabnzbd and python-sabyenc3 and so I see that its out of date every time I check in on things. Just kind of hoping for an idea of what is going on w/ this package. :)

**Comment by sanderjo** [comment]
Does https://sabnzbd.org/wiki/installation/sabyenc.html help you? It should contain all info for you as a package maintainer?

**Comment by fryfrog** [comment]
Bah, should have looked at https://github.com/sabnzbd/sabnzbd/blob/develop/requirements.txt. Clearly it is coming. Thanks! :)

**Comment by sanderjo** [comment]
@fryfrog out of curiosity: do you use pip to create your package?

**Comment by fryfrog** [comment]
That'd be too easy! A `[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sabnzbd)` is very simple and mostly done by hand, even the dependencies need to be packages so sometimes one ends up making new `python-foo` packages to go w/ a software... like [python-sabyenc3](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-sabyenc3). :)

**Comment by Safihre** [comment]
Just a small unrelated note: pyOpenSsl is not used by SABnzbd, cryptography is enough, so it could be removed from the optional depencies :)

**Comment by fryfrog** [comment]
Thanks, appreciate the feedback! :)
