### ISSUE TITLE
Clarify license?

### ISSUE THREAD

**Issue by tdb** [sabnzbd/sabyenc#5]
Can you clarify the license for this project?

https://github.com/sabnzbd/sabyenc/blob/master/LICENSE.md says GPLv3, whilst https://github.com/sabnzbd/sabyenc/blob/master/setup.py#L33 says LGPLv3.

Could the incorrect one be changed?

Thanks.

**Comment by Safihre** [comment]
Fixed, sorry about that.

**Comment by tdb** [comment]
Sorry, just spotted it here too:

https://github.com/sabnzbd/sabyenc/blob/master/setup.py#L40

Thanks for the prompt fix!

**Comment by Safihre** [comment]
I realized that the work is based on Alessandro Duca's work and and as such it should stay LGPLv3 as he released it like that. Changing it to that now.

**Comment by tdb** [comment]
That makes sense. Thanks for sorting it.
