### ISSUE TITLE
Issue with musl + aarch64

### ISSUE THREAD

**Issue by lancethepants** [sabnzbd/sabyenc#73]
So I've cross-compiled python 3.11.0 for aarch64 using musl to run on my asus router (rt-ax88u).  
I ran `pip3 install -r requirements.txt` on the device to install the sabnzbd-3.7.0 requirements. When starting sabnzbd all the requirements are working except sabyenc3, it gives
```
2022-11-18 18:53:32,505::INFO::[notifier:123] Sending notification: Error - SABYenc module... NOT found! Expecting v5.4.4 - https://sabnzbd.org/sabyenc (type=error, job_cat=None)
2022-11-18 18:53:32,505::ERROR::[SABnzbd:436] SABYenc module... NOT found! Expecting v5.4.4 - https://sabnzbd.org/sabyenc
```
With my project [tomatoware](https://github.com/lancethepants/tomatoware) I then try to install the module manually from source on the router. 
First I use command
```
pip3 install --upgrade --force-reinstall --no-cache-dir --ignore-installed --no-binary :all: sabyenc3
```
but I get the same error. 

Since I cross-compiled python3 with compiler `aarch64-tomatoware-linux-musl-gcc`  python remembers this and uses that same compiler name when I compile this module on the router, which is just a symlink to gcc.

Then I try the commands
```
CC=gcc \
pip3 install --upgrade --force-reinstall --no-cache-dir --ignore-installed --no-binary :all: sabyenc3
```
and 
```
CC=aarch64-linux-gcc \
pip3 install --upgrade --force-reinstall --no-cache-dir --ignore-installed --no-binary :all: sabyenc3
```
`aarch64-linux-gcc` is also just a symlink to gcc.

With both these commands sabnzbd then correctly finds and uses the module.

```
2022-11-18 19:13:52,752::INFO::[SABnzbd:423] SABYenc module (v5.4.4)... found!
2022-11-18 19:13:52,752::INFO::[SABnzbd:424] SABYenc module is using SIMD set: NEON
```

So there is some issue at compilation when using the full compiler name like `aarch64-tomatoware-linux-musl-gcc`. I wonder if this is also why the pre-compiled sabyenc3 downloaded through pip doesn't seem to work, for me at least.

I do also have an arm32 router running musl, but I haven't tried running sabnzbd there yet to see if this specific to aarch64 or a musl issue, or maybe something else.

**Comment by sanderjo** [comment]
> I wonder if this is also why the pre-compiled sabyenc3 downloaded through pip doesn't seem to work, for me at least.

I tried with an Alpine (thus: musl) docker on aarch64, and the pip version sabyenc3 just works:

```
/ # pip3 install sabyenc3
Collecting sabyenc3
  Downloading sabyenc3-5.4.4-cp310-cp310-musllinux_1_1_aarch64.whl (681 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 681.1/681.1 kB 84.5 kB/s eta 0:00:00
Installing collected packages: sabyenc3
Successfully installed sabyenc3-5.4.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip3 install --upgrade pip
```

So on your aarch64 with musl: what is the result of that command?

Proof it works:
```
/ # python3
Python 3.10.8 (main, Nov 10 2022, 12:59:17) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabyenc3
>>> sabyenc3.simd
'NEON'
>>> 
```

Environment that I used: Starting the Alpine docker image, and install python3 and pip3:

```
sander@nanopineo2:~$ docker run -it alpine:latest /bin/sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
6875df1f5354: Pull complete 
Digest: sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b
Status: Downloaded newer image for alpine:latest

/ # uname -a
Linux 8e5d7b2805dc 5.15.25-sunxi64 #22.02.1 SMP Sun Feb 27 09:24:04 UTC 2022 aarch64 Linux


/ # apk add --update --no-cache python3 
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/13) Installing libbz2 (1.0.8-r1)
(2/13) Installing expat (2.5.0-r0)
(3/13) Installing libffi (3.4.2-r1)
(4/13) Installing gdbm (1.23-r0)
(5/13) Installing xz-libs (5.2.5-r1)
(6/13) Installing libgcc (11.2.1_git20220219-r2)
(7/13) Installing libstdc++ (11.2.1_git20220219-r2)
(8/13) Installing mpdecimal (2.5.1-r1)
(9/13) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(10/13) Installing ncurses-libs (6.3_p20220521-r0)
(11/13) Installing readline (8.1.2-r0)
(12/13) Installing sqlite-libs (3.38.5-r0)
(13/13) Installing python3 (3.10.8-r0)
Executing busybox-1.35.0-r17.trigger
OK: 57 MiB in 27 packages

/ # python3 -m ensurepip
Looking in links: /tmp/tmpbovf99h1
Processing /tmp/tmpbovf99h1/setuptools-63.2.0-py3-none-any.whl
Processing /tmp/tmpbovf99h1/pip-22.2.2-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-22.2.2 setuptools-63.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by lancethepants** [comment]
Doing some digging I found there a few open issues with python and musl.
https://github.com/python/cpython/issues/87278
https://github.com/python/cpython/issues/95855
https://github.com/python/cpython/pull/18380

Basically when cross-compiling for the host, python looks at the build machine rather than the host machine for libc detection. I'm using debian so the resulting python is expecting gnu. So python on my device was looking for
`sabyenc3.cpython-311-aarch64-linux-gnu.so` instead of
`sabyenc3.cpython-311-aarch64-linux-musl.so`

Since alpine (cross-) compiles using alpine, this isn't an issue for them.

This patch fixes this up til they come up with a better solution.
https://github.com/lancethepants/tomatoware/blob/master/patches/python3/musl/detect-host-os.patch

As far it sometimes working and not working depending on the name of the compiler I used, I had some bad symlinks.
So part on me and part on part on current open python issues.

Anyway, installing sabyenc3 from now is working for me. Thanks for the response that got me to dig deeper.

**Comment by Safihre** [comment]
At SynoCommunity we use the `crossenv` Pypi project, might also be interesting for you!

**Comment by lancethepants** [comment]
@Safihre 
Wow, how have I not heard of crossenv before? I will definitely give that a go. I've mostly worked around needing to cross-compile python modules with my project [Tomatoware](https://github.com/lancethepants/tomatoware) which provides a native compiler for embedded devices (I mostly target asuswrt and tomato firmware supported routers). Compiling all the packages for sabnzbd can take a bit of time though you can imagine.  crossenv looks it would be a good solution for me, thanks for the tip!

**Comment by Safihre** [comment]
Note that crossenv doesn't yet work for Python 3.11, there's PR's open to fix it.
