### ISSUE TITLE
Cannot link to OpenSSL on macOS

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabyenc#76]
@animetosho Maybe you know what is going wrong. I thought I could just simply add macOS support, but for some reason it does not seem to search the right folders.
https://github.com/sabnzbd/sabyenc/commit/0146b0ea147515653c903fce923d5c56552de449
Because I located the file as such here, just like on Windows:
<img width="773" alt="Screenshot 2023-01-03 at 14 39 03" src="https://user-images.githubusercontent.com/5703454/210368373-313afca2-4dfb-4cb9-826a-70eff9f300a9.png">

**Comment by animetosho** [comment]
Does macOS use some sort of container/packaging system? If so, maybe it has a private libssl that isn't visible on the system.

Maybe try running the following and using the *libssl* filename printed there.

	otool -L `python3 -c "import ssl; print(ssl._ssl.__file__)"`

**Comment by Safihre** [comment]
Interesting, here it is:
```
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_ssl.cpython-39-darwin.so:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Comment by animetosho** [comment]
Does it work if you use the full path instead of just `libssl.1.1.dylib`?

Can you double check that the function is exported?  
`nm --extern-only /Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.1.1.dylib | grep read`

Also try the following:

	import ctypes
	h=ctypes.CDLL('libssl.1.1.dylib')
	print(h)
	print(h.SSL_read_ex)

(I don't know that much about macOS, so poking in the dark here)

**Comment by Safihre** [comment]
I found a solution by accessing Python runtime information.
Not the most pretty, but it works: 779fdf734b1e4bebc04ac6ed8b5a1e5543042088
Thanks for helping me brainstorm :)

**Comment by animetosho** [comment]
Nice!

Since the full path seems to work, another possibility may be to pass through `ssl._ssl.__file__` to the module - it might work because I think its dependencies get re-exported.

**Comment by Safihre** [comment]
I understood from this comment on that Cpython thread that you linked before, that on macOS the symbols do not get re-exported: https://github.com/python/cpython/issues/88068#issuecomment-1093911787
So that's why I did not try `ssl._ssl.__file__`.

**Comment by animetosho** [comment]
Ah I see.

**Comment by mnightingale** [comment]
What happened with this? its not on the openssl_link branch did it get lost in a rebase?

I tested it and it didn't work on my [brew](brew.sh) python@3.10 install.

The extension tried: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libssl.1.1.dylib

ssl._ssl.\_\_file\_\_: /usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload/_ssl.cpython-310-darwin.so

There are symlinks going on but based on how it's creating the path it could have found it in:

/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload/_ssl.cpython-310-darwin.so

Tested it with that path hardcode and it worked.
