### ISSUE TITLE
"warning: ‘crc_update’ defined but not used [-Wunused-function]"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabyenc#9]
Hi,

Can we get rid of the error message `warning: ‘crc_update’ defined but not used [-Wunused-function]`, please?

Problem seems to be:
```
#if CRC_CHECK
            // Check CRC value
            crc_update(crc, *(output_buffer-1));
#endif
```
So if CRC_CHECK is False, that 'usage' code is not there,but the function declaration and function definition are still there and unused. 

I could get rid of the warning by adding three `#if CRC_CHECK` ... but why is the function call crc_update() in `#if CRC_CHECK` at all? Does is cause problem if it is called always?

```
sander@witte:~/git/sabyenc$ python setup.py build
running build
running build_ext
building 'sabyenc' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/sabyenc.c -o build/temp.linux-x86_64-2.7/src/sabyenc.o
src/sabyenc.c:100:13: warning: ‘crc_update’ defined but not used [-Wunused-function]
 static void crc_update(Crc32 *crc, uInt c) {
             ^~~~~~~~~~
creating build/lib.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/sabyenc.o -o build/lib.linux-x86_64-2.7/sabyenc.so
sander@witte:~/git/sabyenc$ 
```

**Comment by jcfp** [comment]
> but why is the function call crc_update() in #if CRC_CHECK at all? Does is cause problem if it is called always?

Looking at the code, doing an actual crc check is skipped for performance. Instead, if the size of the data matches expectations, the code simply assumes the crc will also be correct.

CRC_CHECK is only defined if one explicitly sets it at compile time, as a way to disable the default behaviour. I'd expect any compiler to optimize the unused function away, so the warning is pretty much harmless.

**Comment by Safihre** [comment]
Without adding all the extra wrapping, no.
